language: java
jdk:
  - openjdk17


# Travis CI를 어느 브랜치가 push 될 때 수행할 지 지정한다.
branches:
  only:
    - master

# Travis CI 서버의 Home
# gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 다음 배포 때부터 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master branch에 push 되었을 대 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - thisis.joos@gmail.com